version: '2'

services:
  postgres:
    container_name: halomobil
    working_dir: /usr/app
    volumes:
        - postgres_data:/var/lib/postgresql/db-data
    image: 'postgres:9.6.10-alpine'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB : halomobil
      PG_VERSION: '9.6.10-alpine'
    ports:
        - "5432:5432"
volumes:
  postgres_data:

# docker exec -it go_clean_arch bash
# psql postgres -U user -p 5432 go_clean_arch_db