// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	dto "github.com/Klinisia/backend-ksi/src/auth/v1/dto"
	mock "github.com/stretchr/testify/mock"

	shared "github.com/Klinisia/backend-ksi/src/shared"
)

// AuthUsecase is an autogenerated mock type for the AuthUsecase type
type AuthUsecase struct {
	mock.Mock
}

// SignInByPhoneOtp provides a mock function with given fields: _a0
func (_m *AuthUsecase) SignInByPhoneOtp(_a0 *dto.LoginByPhoneOtpRequest) shared.OutputV1 {
	ret := _m.Called(_a0)

	var r0 shared.OutputV1
	if rf, ok := ret.Get(0).(func(*dto.LoginByPhoneOtpRequest) shared.OutputV1); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(shared.OutputV1)
	}

	return r0
}

// SignInByPhonePassword provides a mock function with given fields: _a0
func (_m *AuthUsecase) SignInByPhonePassword(_a0 *dto.LoginByPhoneRequest) shared.OutputV1 {
	ret := _m.Called(_a0)

	var r0 shared.OutputV1
	if rf, ok := ret.Get(0).(func(*dto.LoginByPhoneRequest) shared.OutputV1); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(shared.OutputV1)
	}

	return r0
}
